const now = new Date();
const daysAgo = (days) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const initialData = {
  companies: [
    {
      id: "company-aakash",
      name: "Aakash Group",
      initials: "AG",
      logo_url: "",
      brand_color: "#0D1B3E",
      created_at: daysAgo(30),
    },
  ],
  builders: [
    {
      id: "builder-urban",
      company_id: "company-aakash",
      full_name: "Rohan Mehta",
      company_name: "Urban Vista Developers",
      legal_name: "Urban Vista Developers Pvt Ltd",
      brand_tagline: "Premium living, planned precisely",
      brand_color: "#0D1B3E",
      website: "https://urbanvista.example",
      established_year: 2014,
      phone: "+91 98765 43210",
      email: "rohan@urbanvista.example",
      office_address: "Sector 62, Noida",
      notes: "Flagship partner for premium towers.",
      created_at: daysAgo(25),
    },
    {
      id: "builder-skyline",
      company_id: "company-aakash",
      full_name: "Neha Arora",
      company_name: "Skyline Habitat",
      legal_name: "Skyline Habitat LLP",
      brand_tagline: "Homes with stronger returns",
      brand_color: "#C9A84C",
      website: "https://skyline.example",
      established_year: 2011,
      phone: "+91 98765 11122",
      email: "neha@skyline.example",
      office_address: "Golf Course Road, Gurugram",
      notes: "",
      created_at: daysAgo(20),
    },
  ],
  brokers: [
    {
      id: "broker-aman",
      company_id: "company-aakash",
      full_name: "Aman Kapoor",
      agency_firm: "Kapoor Realty",
      phone: "+91 98111 22334",
      email: "aman@kapoorrealty.example",
      commission_rate: 2,
      notes: "Strong HNI referral network.",
      created_at: daysAgo(18),
    },
    {
      id: "broker-ria",
      company_id: "company-aakash",
      full_name: "Ria Sethi",
      agency_firm: "PrimeNest Brokers",
      phone: "+91 98222 33445",
      email: "ria@primenest.example",
      commission_rate: 1.75,
      notes: "",
      created_at: daysAgo(16),
    },
  ],
  projects: [
    {
      id: "project-emerald",
      company_id: "company-aakash",
      builder_id: "builder-urban",
      name: "Emerald Heights",
      location: "Sector 150, Noida",
      description: "Low-density residential towers near the expressway with clubhouse and sports amenities.",
      price_from: 12500000,
      price_to: 26500000,
      status: "Active",
      amenities: ["Clubhouse", "Pool", "Gym", "Kids Play Area", "Jogging Track"],
      total_units: 8,
      created_at: daysAgo(14),
      updated_at: daysAgo(2),
    },
    {
      id: "project-aurum",
      company_id: "company-aakash",
      builder_id: "builder-skyline",
      name: "Aurum Square",
      location: "Dwarka Expressway, Gurugram",
      description: "Upcoming mixed-use development with high-street retail and premium residences.",
      price_from: 9500000,
      price_to: 18000000,
      status: "Upcoming",
      amenities: ["Retail Arcade", "Co-working Lounge", "Security", "EV Charging"],
      total_units: 6,
      created_at: daysAgo(10),
      updated_at: daysAgo(3),
    },
    {
      id: "project-celeste",
      company_id: "company-aakash",
      builder_id: "builder-urban",
      name: "Celeste Villas",
      location: "Sohna Road, Gurugram",
      description: "Boutique villa enclave with landscaped courts and private terraces.",
      price_from: 32000000,
      price_to: 56000000,
      status: "Completed",
      amenities: ["Private Garden", "Terrace", "Clubhouse", "Concierge"],
      total_units: 5,
      created_at: daysAgo(45),
      updated_at: daysAgo(12),
    },
  ],
  units: [
    { id: "unit-e-101", project_id: "project-emerald", unit_number: "A-101", floor: 1, area_sqft: 1450, price: 12500000, status: "Sold", buyer_lead_id: "lead-priya", notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-e-102", project_id: "project-emerald", unit_number: "A-102", floor: 1, area_sqft: 1450, price: 12700000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-e-201", project_id: "project-emerald", unit_number: "A-201", floor: 2, area_sqft: 1680, price: 15100000, status: "Reserved", buyer_lead_id: null, notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-e-202", project_id: "project-emerald", unit_number: "A-202", floor: 2, area_sqft: 1680, price: 15300000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-e-301", project_id: "project-emerald", unit_number: "B-301", floor: 3, area_sqft: 2200, price: 23500000, status: "Sold", buyer_lead_id: null, notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-e-302", project_id: "project-emerald", unit_number: "B-302", floor: 3, area_sqft: 2260, price: 25000000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-e-401", project_id: "project-emerald", unit_number: "P-401", floor: 4, area_sqft: 2550, price: 26500000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-e-402", project_id: "project-emerald", unit_number: "P-402", floor: 4, area_sqft: 2550, price: 26500000, status: "Reserved", buyer_lead_id: null, notes: "", created_at: daysAgo(13), updated_at: daysAgo(1) },
    { id: "unit-a-101", project_id: "project-aurum", unit_number: "R-101", floor: 1, area_sqft: 1180, price: 9500000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(8), updated_at: daysAgo(1) },
    { id: "unit-a-102", project_id: "project-aurum", unit_number: "R-102", floor: 1, area_sqft: 1220, price: 9900000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(8), updated_at: daysAgo(1) },
    { id: "unit-a-201", project_id: "project-aurum", unit_number: "R-201", floor: 2, area_sqft: 1650, price: 14500000, status: "Reserved", buyer_lead_id: null, notes: "", created_at: daysAgo(8), updated_at: daysAgo(1) },
    { id: "unit-a-202", project_id: "project-aurum", unit_number: "R-202", floor: 2, area_sqft: 1850, price: 18000000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(8), updated_at: daysAgo(1) },
    { id: "unit-c-1", project_id: "project-celeste", unit_number: "Villa 1", floor: 0, area_sqft: 3200, price: 32000000, status: "Sold", buyer_lead_id: null, notes: "", created_at: daysAgo(38), updated_at: daysAgo(12) },
    { id: "unit-c-2", project_id: "project-celeste", unit_number: "Villa 2", floor: 0, area_sqft: 3600, price: 39000000, status: "Sold", buyer_lead_id: null, notes: "", created_at: daysAgo(38), updated_at: daysAgo(12) },
    { id: "unit-c-3", project_id: "project-celeste", unit_number: "Villa 3", floor: 0, area_sqft: 4100, price: 56000000, status: "Available", buyer_lead_id: null, notes: "", created_at: daysAgo(38), updated_at: daysAgo(12) },
  ],
  leads: [
    {
      id: "lead-priya",
      company_id: "company-aakash",
      full_name: "Priya Malhotra",
      phone: "+91 99100 11223",
      email: "priya@example.com",
      lead_source: "Walk-in",
      broker_id: null,
      budget: 16000000,
      interested_project_id: "project-emerald",
      status: "Converted",
      notes: "Interested in lower floor inventory.",
      photo_url: "",
      latitude: 28.4595,
      longitude: 77.0266,
      location_address: "Gurugram, Haryana",
      created_at: daysAgo(0),
      updated_at: daysAgo(0),
    },
    {
      id: "lead-karan",
      company_id: "company-aakash",
      full_name: "Karan Bhatia",
      phone: "+91 99888 77665",
      email: "karan@example.com",
      lead_source: "Broker",
      broker_id: "broker-aman",
      budget: 25000000,
      interested_project_id: "project-emerald",
      status: "Site Visit",
      notes: "Site visit planned for weekend.",
      photo_url: "",
      latitude: 28.6139,
      longitude: 77.209,
      location_address: "New Delhi",
      created_at: daysAgo(1),
      updated_at: daysAgo(0),
    },
    {
      id: "lead-sana",
      company_id: "company-aakash",
      full_name: "Sana Khan",
      phone: "+91 98711 22233",
      email: "sana@example.com",
      lead_source: "Online",
      broker_id: null,
      budget: 11000000,
      interested_project_id: "project-aurum",
      status: "New",
      notes: "Asked for payment plan.",
      photo_url: "",
      latitude: 28.5355,
      longitude: 77.391,
      location_address: "Noida, Uttar Pradesh",
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
    },
  ],
  lead_activities: [],
};
